### ISSUE TITLE
testing problem

### ISSUE THREAD

**Issue by wuhao11905** [benchen4395/new_chessboards_test#1]
When i use new_atest_newpicture_fast.py to test GOPR1.jpg, it find no corners. Is the result right?(it can find corners in IMG19.jpg)

**Comment by benchen4395** [comment]
Which ckpt model is you used? I remember the second ckpt is the best and can get most corners on all images (of course not all corners, this need new method).
We will release the update version after our new paper released.
Best wishes for you!
